CREATE TABLE IF NOT EXISTS clients (
    client_id VARCHAR(100) PRIMARY KEY,
    ip VARCHAR(45) NOT NULL,
    port INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    sender VARCHAR(100) NOT NULL,
    receiver VARCHAR(100),
    message TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);